int _DefaultRuneLocale;
int __stdinp;
int __stdoutp;
int __stderrp;
int mach_task_self_;
int vm_page_size;
void inet_addr() {}
void inet_ntop() {}
void inet_pton() {}
void setlocale() {}
void __tolower() {}
void __toupper() {}
void __maskrune() {}
void __cxa_atexit() {}
void __cxa_finalize() {}
void CC_MD5() {}
void opendir() {}
void readdir() {}
void closedir() {}
void scandir() {}
void dlopen() {}
void dlsym() {}
void dlclose() {}
void DNSServiceBrowse() {}
void DNSServiceRefSockFD() {}
void __error() {}
void perror() {}
void getifaddrs() {}
void _keymgr_get_and_lock_processwide_ptr_2() {}
void _keymgr_get_and_lock_processwide_ptr() {}
void _keymgr_set_and_unlock_processwide_ptr() {}
void _keymgr_unlock_processwide_ptr() {}
void OSAtomicAdd32() {}
void OSAtomicAdd32Barrier() {}
void OSAtomicCompareAndSwap32() {}
void OSAtomicCompareAndSwapIntBarrier() {}
void OSAtomicCompareAndSwap32Barrier() {}
void OSAtomicCompareAndSwapPtrBarrier() {}
void mach_host_self() {}
void host_page_size() {}
void host_statistics() {}
void mach_task_self() {}
void semaphore_create() {}
void semaphore_signal() {}
void semaphore_wait() {}
void semaphore_destroy() {}
void thread_info() {}
void thread_policy_set() {}
void mach_timebase_info() {}
void mach_absolute_time() {}
void abs() {}
void fabs() {}
void sin() {}
void sinf() {}
void cos() {}
void cosf() {}
void tan() {}
void tanf() {}
void asin() {}
void asinf() {}
void acos() {}
void acosf() {}
void atan() {}
void atanf() {}
void atan2() {}
void atan2f() {}
void sinh() {}
void sinhf() {}
void cosh() {}
void coshf() {}
void tanh() {}
void tanhf() {}
void asinh() {}
void asinhf() {}
void acosh() {}
void acoshf() {}
void atanh() {}
void atanhf() {}
void log() {}
void logf() {}
void log1p() {}
void log1pf() {}
void log2() {}
void log2f() {}
void log10() {}
void log10f() {}
void exp() {}
void expf() {}
void expm1() {}
void expm1f() {}
void exp2() {}
void exp2f() {}
void ldexp() {}
void ldexpf() {}
void frexpf() {}
void frexp() {}
void pow() {}
void powf() {}
void sqrt() {}
void sqrtf() {}
void ceil() {}
void ceilf() {}
void floor() {}
void floorf() {}
void round() {}
void roundf() {}
void lround() {}
void lroundf() {}
void trunc() {}
void truncf() {}
void modf() {}
void modff() {}
void lrint() {}
void lrintf() {}
void fegetround() {}
void fesetround() {}
void fmod() {}
void fmodf() {}
void fmax() {}
void fmaxf() {}
void fmin() {}
void fminf() {}
void mmap() {}
void munmap() {}
void if_nameindex() {}
void getaddrinfo() {}
void freeaddrinfo() {}
void gethostbyname() {}
void open() {}
void read() {}
void pread() {}
void write() {}
void pwrite() {}
void lseek() {}
void close() {}
void rename() {}
void getcwd() {}
void chdir() {}
void fcntl() {}
void flock() {}
void fsync() {}
void ftruncate() {}
void mkdir() {}
void fstat() {}
void stat() {}
void pthread_cond_init() {}
void pthread_cond_wait() {}
void pthread_cond_signal() {}
void pthread_cond_broadcast() {}
void pthread_cond_destroy() {}
void pthread_key_create() {}
void pthread_getspecific() {}
void pthread_setspecific() {}
void pthread_mutexattr_init() {}
void pthread_mutexattr_setpshared() {}
void pthread_mutexattr_settype() {}
void pthread_mutexattr_destroy() {}
void pthread_mutex_init() {}
void pthread_mutex_lock() {}
void pthread_mutex_trylock() {}
void pthread_mutex_unlock() {}
void pthread_mutex_destroy() {}
void pthread_once() {}
void pthread_attr_init() {}
void pthread_attr_setdetachstate() {}
void pthread_attr_getstacksize() {}
void pthread_attr_setstacksize() {}
void pthread_attr_destroy() {}
void pthread_create() {}
void pthread_equal() {}
void pthread_self() {}
void pthread_join() {}
void pthread_detach() {}
void pthread_setcanceltype() {}
void pthread_testcancel() {}
void pthread_mach_thread_np() {}
void pthread_getschedparam() {}
void pthread_setschedparam() {}
void sched_yield() {}
void sem_init() {}
void sem_destroy() {}
void sem_open() {}
void sem_post() {}
void sem_wait() {}
void sem_trywait() {}
void sem_close() {}
void sem_unlink() {}
void setjmp() {}
void longjmp() {}
void sigaction() {}
void signal() {}
void fopen() {}
void fread() {}
void fgetc() {}
void getc() {}
void ungetc() {}
void fgets() {}
void fputs() {}
void fputc() {}
void putc() {}
void fwrite() {}
void fseek() {}
void ftell() {}
void rewind() {}
void fsetpos() {}
void fgetpos() {}
void feof() {}
void clearerr() {}
void fflush() {}
void fclose() {}
void ferror() {}
void puts() {}
void putchar() {}
void remove() {}
void setbuf() {}
void fileno() {}
void sscanf() {}
void swscanf() {}
void vsscanf() {}
void fscanf() {}
void snprintf() {}
void vprintf() {}
void vsnprintf() {}
void vsprintf() {}
void __sprintf_chk() {}
void sprintf() {}
void swprintf() {}
void vswprintf() {}
void printf() {}
void fprintf() {}
void vfprintf() {}
void malloc() {}
void malloc_size() {}
void calloc() {}
void realloc() {}
void free() {}
void atexit() {}
void atoi() {}
void atol() {}
void atof() {}
void strtod() {}
void srand() {}
void rand() {}
void srandom() {}
void random() {}
void arc4random() {}
void getenv() {}
void setenv() {}
void exit() {}
void bsearch() {}
void strtof() {}
void strtoul() {}
void strtoull() {}
void strtol() {}
void realpath() {}
void realpath$DARWIN_EXTSN() {}
void mbstowcs() {}
void wcstombs() {}
void system() {}
void qsort() {}
void strtok() {}
void bzero() {}
void memset() {}
void __memset_chk() {}
void memset_pattern4() {}
void memset_pattern8() {}
void memset_pattern16() {}
void memcpy() {}
void memmove() {}
void memchr() {}
void memcmp() {}
void strlen() {}
void strcpy() {}
void __strcpy_chk() {}
void strcat() {}
void strcspn() {}
void __strcat_chk() {}
void strncpy() {}
void strsep() {}
void strdup() {}
void strcmp() {}
void strncmp() {}
void strcasecmp() {}
void strncasecmp() {}
void strncat() {}
void strstr() {}
void strchr() {}
void strrchr() {}
void strlcpy() {}
void statfs() {}
void ptrace() {}
void ftime() {}
void socket() {}
void ioctl() {}
void getsockopt() {}
void setsockopt() {}
void bind() {}
void listen() {}
void connect() {}
void select() {}
void accept() {}
void recv() {}
void recvfrom() {}
void send() {}
void sendto() {}
void shutdown() {}
void uname() {}
void sysctl() {}
void sysctlbyname() {}
void clock() {}
void time() {}
void tzset() {}
void gmtime_r() {}
void gmtime() {}
void mktime() {}
void localtime_r() {}
void localtime() {}
void gettimeofday() {}
void nanosleep() {}
void sleep() {}
void usleep() {}
void getpid() {}
void getppid() {}
void isatty() {}
void access() {}
void unlink() {}
void gethostname() {}
void getpagesize() {}
void getgid() {}
void btowc() {}
void wctob() {}
void wmemset() {}
void wmemcpy() {}
void wmemmove() {}
void wmemchr() {}
void wmemcmp() {}
void wcslen() {}
void wcscpy() {}
void wcscat() {}
void wcscspn() {}
void wcsncpy() {}
void wcsdup() {}
void wcscmp() {}
void wcsncmp() {}
void wcsncat() {}
void wcsstr() {}
void wcschr() {}
void wcsrchr() {}
void wcslcpy() {}
void strerror() {}
void fsctl() {}
void srandomdev() {}
void confstr() {}
void strlcat() {}
void utimes() {}
void fchmod() {}
void dlerror() {}
void poll() {}
void getsockname() {}
void nan() {}
void dup() {}
void __fpclassify() {}
