void setlocale() {}
void __tolower() {}
void __toupper() {}
void __cxa_atexit() {}
void __cxa_finalize() {}
void CC_MD5() {}
void opendir() {}
void readdir() {}
void closedir() {}
void scandir() {}
void dlopen() {}
void dlsym() {}
void dlclose() {}
void __error() {}
void perror() {}
void getifaddrs() {}
void _keymgr_get_and_lock_processwide_ptr_2() {}
void _keymgr_get_and_lock_processwide_ptr() {}
void _keymgr_set_and_unlock_processwide_ptr() {}
void _keymgr_unlock_processwide_ptr() {}
void mach_host_self() {}
void host_page_size() {}
void host_statistics() {}
void semaphore_create() {}
void semaphore_signal() {}
void semaphore_wait() {}
void semaphore_destroy() {}
void thread_info() {}
void thread_policy_set() {}
void mach_timebase_info() {}
void mach_absolute_time() {}
void abs() {}
void sin() {}
void sinf() {}
void cos() {}
void cosf() {}
void tan() {}
void tanf() {}
void asin() {}
void asinf() {}
void acos() {}
void acosf() {}
void atan() {}
void atanf() {}
void atan2() {}
void atan2f() {}
void sinh() {}
void sinhf() {}
void cosh() {}
void coshf() {}
void tanh() {}
void tanhf() {}
void asinh() {}
void asinhf() {}
void acosh() {}
void acoshf() {}
void atanh() {}
void atanhf() {}
void log() {}
void logf() {}
void log1p() {}
void log1pf() {}
void log2() {}
void log2f() {}
void log10() {}
void log10f() {}
void exp() {}
void expf() {}
void expm1() {}
void expm1f() {}
void exp2() {}
void exp2f() {}
void ldexp() {}
void ldexpf() {}
void pow() {}
void powf() {}
void sqrt() {}
void sqrtf() {}
void ceil() {}
void ceilf() {}
void floor() {}
void floorf() {}
void round() {}
void roundf() {}
void trunc() {}
void truncf() {}
void modff() {}
void lrint() {}
void lrintf() {}
void fmod() {}
void fmodf() {}
void fmax() {}
void fmaxf() {}
void fmin() {}
void fminf() {}
void mmap() {}
void if_nameindex() {}
void gethostbyname() {}
void open() {}
void read() {}
void write() {}
void lseek() {}
void close() {}
void rename() {}
void getcwd() {}
void chdir() {}
void fcntl() {}
void flock() {}
void ftruncate() {}
void mkdir() {}
void fstat() {}
void stat() {}
void pthread_cond_init() {}
void pthread_cond_wait() {}
void pthread_cond_signal() {}
void pthread_cond_destroy() {}
void pthread_key_create() {}
void pthread_getspecific() {}
void pthread_setspecific() {}
void pthread_mutexattr_init() {}
void pthread_mutexattr_settype() {}
void pthread_mutexattr_destroy() {}
void pthread_mutex_init() {}
void pthread_mutex_lock() {}
void pthread_mutex_trylock() {}
void pthread_mutex_unlock() {}
void pthread_mutex_destroy() {}
void pthread_once() {}
void pthread_attr_init() {}
void pthread_attr_setdetachstate() {}
void pthread_attr_getstacksize() {}
void pthread_attr_setstacksize() {}
void pthread_attr_destroy() {}
void pthread_create() {}
void pthread_self() {}
void pthread_join() {}
void pthread_detach() {}
void pthread_setcanceltype() {}
void pthread_testcancel() {}
void pthread_mach_thread_np() {}
void pthread_getschedparam() {}
void pthread_setschedparam() {}
void sched_yield() {}
void sem_open() {}
void sem_post() {}
void sem_wait() {}
void sem_trywait() {}
void sem_close() {}
void sem_unlink() {}
void setjmp() {}
void sigaction() {}
void signal() {}
void fopen() {}
void fread() {}
void fgetc() {}
void fgets() {}
void fputs() {}
void fputc() {}
void putc() {}
void fwrite() {}
void fseek() {}
void ftell() {}
void rewind() {}
void fsetpos() {}
void fgetpos() {}
void feof() {}
void clearerr() {}
void fflush() {}
void fclose() {}
void ferror() {}
void puts() {}
void putchar() {}
void remove() {}
void setbuf() {}
void fileno() {}
void sscanf() {}
void swscanf() {}
void vsscanf() {}
void snprintf() {}
void vprintf() {}
void vsnprintf() {}
void vsprintf() {}
void __sprintf_chk() {}
void sprintf() {}
void swprintf() {}
void vswprintf() {}
void printf() {}
void fprintf() {}
void vfprintf() {}
void malloc() {}
void calloc() {}
void realloc() {}
void free() {}
void atexit() {}
void atoi() {}
void atol() {}
void atof() {}
void strtod() {}
void srand() {}
void rand() {}
void srandom() {}
void random() {}
void arc4random() {}
void getenv() {}
void setenv() {}
void exit() {}
void bsearch() {}
void strtof() {}
void strtoul() {}
void strtol() {}
void realpath() {}
void realpath$DARWIN_EXTSN() {}
void mbstowcs() {}
void wcstombs() {}
void qsort() {}
void strtok() {}
void bzero() {}
void memset() {}
void memcpy() {}
void memmove() {}
void memchr() {}
void memcmp() {}
void strlen() {}
void strcpy() {}
void __strcpy_chk() {}
void strcat() {}
void strcspn() {}
void __strcat_chk() {}
void strncpy() {}
void strsep() {}
void strdup() {}
void strcmp() {}
void strncmp() {}
void strcasecmp() {}
void strncasecmp() {}
void strncat() {}
void strstr() {}
void strchr() {}
void strrchr() {}
void strlcpy() {}
void statfs() {}
void ftime() {}
void uname() {}
void sysctl() {}
void sysctlbyname() {}
void clock() {}
void time() {}
void tzset() {}
void gmtime_r() {}
void gmtime() {}
void mktime() {}
void localtime_r() {}
void localtime() {}
void gettimeofday() {}
void nanosleep() {}
void sleep() {}
void usleep() {}
void getpid() {}
void getppid() {}
void isatty() {}
void access() {}
void unlink() {}
void btowc() {}
void wctob() {}
void wmemset() {}
void wmemcpy() {}
void wmemmove() {}
void wmemchr() {}
void wmemcmp() {}
void wcslen() {}
void wcscpy() {}
void wcscat() {}
void wcscspn() {}
void wcsncpy() {}
void wcsdup() {}
void wcscmp() {}
void wcsncmp() {}
void wcsncat() {}
void wcsstr() {}
void wcschr() {}
void wcsrchr() {}
void wcslcpy() {}
void objc_msgSend() {}
void objc_msgSend_stret() {}
void objc_msgSendSuper2() {}
void objc_getProperty() {}
void objc_setProperty() {}
void objc_copyStruct() {}
void objc_sync_enter() {}
void objc_sync_exit() {}
void sel_registerName() {}
void AudioComponentFindNext() {}
void AudioComponentInstanceNew() {}
void AudioComponentInstanceDispose() {}
void AudioFileOpenURL() {}
void AudioFileGetPropertyInfo() {}
void AudioFileGetProperty() {}
void AudioFileReadBytes() {}
void AudioFileReadPackets() {}
void AudioFileReadPacketData() {}
void AudioFileOpenWithCallbacks() {}
void AudioFileClose() {}
void AudioFileStreamOpen() {}
void AudioQueueNewOutput() {}
void AudioQueueGetParameter() {}
void AudioQueueSetParameter() {}
void AudioQueueAllocateBufferWithPacketDescriptions() {}
void AudioQueueAllocateBuffer() {}
void AudioQueueEnqueueBuffer() {}
void AudioQueueAddPropertyListener() {}
void AudioQueueRemovePropertyListener() {}
void AudioQueueGetPropertySize() {}
void AudioQueueGetProperty() {}
void AudioQueuePrime() {}
void AudioQueueStart() {}
void AudioQueuePause() {}
void AudioQueueStop() {}
void AudioQueueReset() {}
void AudioQueueFlush() {}
void AudioQueueFreeBuffer() {}
void AudioQueueDispose() {}
void AudioServicesGetProperty() {}
void AudioServicesPlaySystemSound() {}
void AudioSessionInitialize() {}
void AudioSessionGetProperty() {}
void AudioSessionSetProperty() {}
void AudioSessionSetActive() {}
void AudioSessionAddPropertyListener() {}
void AudioUnitInitialize() {}
void AudioUnitUninitialize() {}
void AudioUnitSetProperty() {}
void AudioUnitGetProperty() {}
void AudioOutputUnitStart() {}
void AudioOutputUnitStop() {}
void CFArrayCreateMutable() {}
void CFArrayGetCount() {}
void CFArrayGetValueAtIndex() {}
void CFArrayAppendValue() {}
void CFArrayRemoveValueAtIndex() {}
void CFDictionaryCreateMutable() {}
void CFDictionaryAddValue() {}
void CFDictionarySetValue() {}
void CFDictionaryRemoveValue() {}
void CFDictionaryRemoveAllValues() {}
void CFDictionaryGetValue() {}
void CFDictionaryGetCount() {}
void CFDictionaryGetKeysAndValues() {}
void CFBundleGetMainBundle() {}
void CFBundleGetValueForInfoDictionaryKey() {}
void CFBundleGetVersionNumber() {}
void CFBundleCopyBundleURL() {}
void CFBundleCopyResourcesDirectoryURL() {}
void CFBundleCopyResourceURL() {}
void CFBundleCopyBundleLocalizations() {}
void CFBundleCopyPreferredLocalizationsFromArray() {}
void CFDataCreate() {}
void CFDataGetLength() {}
void CFDataGetBytePtr() {}
void CFDataGetBytes() {}
void CFLocaleCopyPreferredLanguages() {}
void CFLocaleCreateCanonicalLocaleIdentifierFromString() {}
void CFRunLoopGetCurrent() {}
void CFRunLoopGetMain() {}
void CFRunLoopRunInMode() {}
void CFRunLoopTimerCreate() {}
void CFRunLoopAddTimer() {}
void CFRunLoopTimerInvalidate() {}
void CFStringAppendFormat() {}
void CFStringConvertEncodingToNSStringEncoding() {}
void CFStringConvertNSStringEncodingToEncoding() {}
void CFStringCreateMutable() {}
void CFStringCreateWithCString() {}
void CFStringCreateWithFormat() {}
void CFStringCreateWithFormatAndArguments() {}
void CFStringCompare() {}
void CFStringGetCStringPtr() {}
void CFStringGetCString() {}
void CFStringGetLength() {}
void CFStringFind() {}
void CFRetain() {}
void CFRelease() {}
void CFGetRetainCount() {}
void CFEqual() {}
void CFHash() {}
void CFURLGetFileSystemRepresentation() {}
void CFURLCreateFromFileSystemRepresentation() {}
void CFURLCopyPathExtension() {}
void CFURLCopyFileSystemPath() {}
void CFAbsoluteTimeGetCurrent() {}
void CFTimeZoneCopySystem() {}
void CFAbsoluteTimeGetGregorianDate() {}
void CFAbsoluteTimeGetDayOfWeek() {}
void CGAffineTransformIsIdentity() {}
void CGAffineTransformEqualToTransform() {}
void CGAffineTransformMake() {}
void CGAffineTransformMakeRotation() {}
void CGAffineTransformMakeScale() {}
void CGAffineTransformMakeTranslation() {}
void CGAffineTransformConcat() {}
void CGAffineTransformRotate() {}
void CGAffineTransformScale() {}
void CGAffineTransformTranslate() {}
void CGAffineTransformInvert() {}
void CGPointApplyAffineTransform() {}
void CGSizeApplyAffineTransform() {}
void CGRectApplyAffineTransform() {}
void CGBitmapContextCreate() {}
void CGBitmapContextCreateImage() {}
void CGBitmapContextGetData() {}
void CGBitmapContextGetWidth() {}
void CGBitmapContextGetHeight() {}
void CGColorRetain() {}
void CGColorRelease() {}
void CGColorCreate() {}
void CGColorSpaceCreateWithName() {}
void CGColorSpaceCreateDeviceRGB() {}
void CGColorSpaceCreateDeviceGray() {}
void CGColorSpaceRetain() {}
void CGColorSpaceRelease() {}
void CGColorSpaceGetModel() {}
void CGContextRetain() {}
void CGContextRelease() {}
void CGContextSetRGBFillColor() {}
void CGContextSetGrayFillColor() {}
void CGContextFillRect() {}
void CGContextClearRect() {}
void CGContextConcatCTM() {}
void CGContextGetCTM() {}
void CGContextRotateCTM() {}
void CGContextScaleCTM() {}
void CGContextTranslateCTM() {}
void CGContextDrawImage() {}
void CGContextSaveGState() {}
void CGContextRestoreGState() {}
void CGContextSetInterpolationQuality() {}
void CGDataProviderRetain() {}
void CGDataProviderRelease() {}
void CGDataProviderCreateWithData() {}
void CGDataProviderCopyData() {}
void CGPointEqualToPoint() {}
void CGSizeEqualToSize() {}
void CGRectEqualToRect() {}
void CGRectContainsPoint() {}
void CGImageRelease() {}
void CGImageRetain() {}
void CGImageCreateWithPNGDataProvider() {}
void CGImageGetAlphaInfo() {}
void CGImageGetColorSpace() {}
void CGImageGetWidth() {}
void CGImageGetHeight() {}
void CGImageGetBitsPerPixel() {}
void CGImageGetDataProvider() {}
void CGImageGetBitsPerComponent() {}
void DNSServiceBrowse() {}
void DNSServiceRefSockFD() {}
void NSStringFromRange() {}
void NSSetUncaughtExceptionHandler() {}
void NSHomeDirectory() {}
void NSTemporaryDirectory() {}
void NSSearchPathForDirectoriesInDomains() {}
void NSLog() {}
void NSLogv() {}
void NSStringFromSelector() {}
void NSSelectorFromString() {}
void NSClassFromString() {}
void NSStringFromClass() {}
void alcOpenDevice() {}
void alcCloseDevice() {}
void alcGetError() {}
void alcCreateContext() {}
void alcDestroyContext() {}
void alcProcessContext() {}
void alcSuspendContext() {}
void alcMakeContextCurrent() {}
void alcGetProcAddress() {}
void alGetError() {}
void alDistanceModel() {}
void alListenerf() {}
void alListener3f() {}
void alListenerfv() {}
void alListeneri() {}
void alListener3i() {}
void alListeneriv() {}
void alGetListenerf() {}
void alGetListener3f() {}
void alGetListenerfv() {}
void alGetListeneri() {}
void alGetListener3i() {}
void alGetListeneriv() {}
void alGenSources() {}
void alDeleteSources() {}
void alSourcef() {}
void alSource3f() {}
void alSourcefv() {}
void alSourcei() {}
void alSource3i() {}
void alSourceiv() {}
void alGetSourcef() {}
void alGetSource3f() {}
void alGetSourcefv() {}
void alGetSourcei() {}
void alGetSource3i() {}
void alGetSourceiv() {}
void alSourcePlay() {}
void alSourcePause() {}
void alSourceStop() {}
void alSourceRewind() {}
void alSourceQueueBuffers() {}
void alSourceUnqueueBuffers() {}
void alGenBuffers() {}
void alDeleteBuffers() {}
void alBufferData() {}
void alBufferDataStatic() {}
void alcMacOSXMixerOutputRate() {}
void alcMacOSXGetMixerOutputRate() {}
void alcGetContextsDevice() {}
void alcGetCurrentContext() {}
void alcGetEnumValue() {}
void alcGetIntegerv() {}
void alcGetString() {}
void alcIsExtensionPresent() {}
void alIsBuffer() {}
void alGetBufferf() {}
void alGetBufferi() {}
void alEnable() {}
void alDisable() {}
void alDopplerFactor() {}
void alDopplerVelocity() {}
void alGetBoolean() {}
void alGetBooleanv() {}
void alGetDouble() {}
void alGetDoublev() {}
void alGetFloat() {}
void alGetFloatv() {}
void alGetInteger() {}
void alGetIntegerv() {}
void alGetEnumValue() {}
void alGetProcAddress() {}
void alGetString() {}
void alIsExtensionPresent() {}
void alIsEnabled() {}
void alIsSource() {}
void alSourcePlayv() {}
void alSourcePausev() {}
void alSourceStopv() {}
void alSourceRewindv() {}
void alSpeedOfSound() {}
void glGetError() {}
void glEnable() {}
void glIsEnabled() {}
void glDisable() {}
void glClientActiveTexture() {}
void glEnableClientState() {}
void glDisableClientState() {}
void glGetBooleanv() {}
void glGetFloatv() {}
void glGetIntegerv() {}
void glGetPointerv() {}
void glGetTexEnviv() {}
void glGetTexEnvfv() {}
void glHint() {}
void glFinish() {}
void glFlush() {}
void glGetString() {}
void glAlphaFunc() {}
void glAlphaFuncx() {}
void glBlendFunc() {}
void glBlendEquationOES() {}
void glColorMask() {}
void glClipPlanef() {}
void glClipPlanex() {}
void glCullFace() {}
void glDepthFunc() {}
void glDepthMask() {}
void glDepthRangef() {}
void glDepthRangex() {}
void glFrontFace() {}
void glPolygonOffset() {}
void glPolygonOffsetx() {}
void glShadeModel() {}
void glScissor() {}
void glViewport() {}
void glLineWidth() {}
void glLineWidthx() {}
void glStencilFunc() {}
void glStencilOp() {}
void glStencilMask() {}
void glPointSize() {}
void glPointSizex() {}
void glPointParameterf() {}
void glPointParameterx() {}
void glPointParameterfv() {}
void glPointParameterxv() {}
void glFogf() {}
void glFogx() {}
void glFogfv() {}
void glFogxv() {}
void glLightf() {}
void glLightx() {}
void glLightfv() {}
void glLightxv() {}
void glLightModelf() {}
void glLightModelfv() {}
void glLightModelx() {}
void glLightModelxv() {}
void glMaterialf() {}
void glMaterialx() {}
void glMaterialfv() {}
void glMaterialxv() {}
void glGenBuffers() {}
void glDeleteBuffers() {}
void glBindBuffer() {}
void glBufferData() {}
void glBufferSubData() {}
void glColor4f() {}
void glColor4x() {}
void glColor4ub() {}
void glNormal3f() {}
void glNormal3x() {}
void glColorPointer() {}
void glNormalPointer() {}
void glTexCoordPointer() {}
void glVertexPointer() {}
void glDrawArrays() {}
void glDrawElements() {}
void glClear() {}
void glClearColor() {}
void glClearColorx() {}
void glClearDepthf() {}
void glClearDepthx() {}
void glClearStencil() {}
void glMatrixMode() {}
void glLoadIdentity() {}
void glLoadMatrixf() {}
void glLoadMatrixx() {}
void glMultMatrixf() {}
void glMultMatrixx() {}
void glPushMatrix() {}
void glPopMatrix() {}
void glOrthof() {}
void glOrthox() {}
void glFrustumf() {}
void glFrustumx() {}
void glRotatef() {}
void glRotatex() {}
void glScalef() {}
void glScalex() {}
void glTranslatef() {}
void glTranslatex() {}
void glPixelStorei() {}
void glGenTextures() {}
void glDeleteTextures() {}
void glActiveTexture() {}
void glIsTexture() {}
void glBindTexture() {}
void glTexParameteri() {}
void glTexParameterf() {}
void glTexParameterx() {}
void glTexParameteriv() {}
void glTexParameterfv() {}
void glTexParameterxv() {}
void glTexImage2D() {}
void glTexSubImage2D() {}
void glCompressedTexImage2D() {}
void glCopyTexImage2D() {}
void glCopyTexSubImage2D() {}
void glTexEnvf() {}
void glTexEnvx() {}
void glTexEnvi() {}
void glTexEnvfv() {}
void glTexEnvxv() {}
void glTexEnviv() {}
void glGenFramebuffersOES() {}
void glGenRenderbuffersOES() {}
void glBindFramebufferOES() {}
void glBindRenderbufferOES() {}
void glRenderbufferStorageOES() {}
void glFramebufferRenderbufferOES() {}
void glFramebufferTexture2DOES() {}
void glGetFramebufferAttachmentParameterivOES() {}
void glGetRenderbufferParameterivOES() {}
void glCheckFramebufferStatusOES() {}
void glDeleteFramebuffersOES() {}
void glDeleteRenderbuffersOES() {}
void glGenerateMipmapOES() {}
void glGetBufferParameteriv() {}
void glMapBufferOES() {}
void glUnmapBufferOES() {}
void SCNetworkReachabilityCreateWithName() {}
void SCNetworkReachabilityCreateWithAddress() {}
void SCNetworkReachabilityGetFlags() {}
void UIApplicationMain() {}
void CGPointFromString() {}
void CGSizeFromString() {}
void CGRectFromString() {}
void NSStringFromCGPoint() {}
void NSStringFromCGSize() {}
void NSStringFromCGRect() {}
void UIGraphicsPushContext() {}
void UIGraphicsPopContext() {}
void UIGraphicsGetCurrentContext() {}
void strerror() {}
void _DefaultRuneLocale() {}
void __maskrune() {}
void fsctl() {}
void srandomdev() {}
void confstr() {}
void strlcat() {}
void pwrite() {}
void utimes() {}
void pread() {}
void fchmod() {}
void dlerror() {}
void fsync() {}
