void malloc() { }
void free() { }
void calloc() { }
void memcpy() { }
void memset() { }
void strlen() { }
void strcmp() { }
void strlcat() { }
void strlcpy() { }
void strerror() { }
void fopen() { }
void fclose() { }
void clearerr() { }
void ferror() { }
void fflush() { }
void fputc() { }
void fread() { }
void fseek() { }
void ftell() { }
void fwrite() { }
void fprintf() { }
void snprintf() { }
void vsnprintf() { }
void dlopen() { }
void dlsym() { }
void __error() { }
