void inet_addr() {}
void inet_ntop() {}
void inet_pton() {}
void setlocale() {}
void __tolower() {}
void __toupper() {}
void __maskrune() {}
void __cxa_atexit() {}
void __cxa_finalize() {}
void CC_MD5() {}
void opendir() {}
void readdir() {}
void closedir() {}
void scandir() {}
void dlopen() {}
void dlsym() {}
void dlclose() {}
void __error() {}
void perror() {}
void getifaddrs() {}
void _keymgr_get_and_lock_processwide_ptr_2() {}
void _keymgr_get_and_lock_processwide_ptr() {}
void _keymgr_set_and_unlock_processwide_ptr() {}
void _keymgr_unlock_processwide_ptr() {}
void OSAtomicAdd32Barrier() {}
void OSAtomicCompareAndSwap32() {}
void OSAtomicCompareAndSwap32Barrier() {}
void mach_host_self() {}
void host_page_size() {}
void host_statistics() {}
void semaphore_create() {}
void semaphore_signal() {}
void semaphore_wait() {}
void semaphore_destroy() {}
void thread_info() {}
void thread_policy_set() {}
void mach_timebase_info() {}
void mach_absolute_time() {}
void abs() {}
void fabs() {}
void sin() {}
void sinf() {}
void cos() {}
void cosf() {}
void tan() {}
void tanf() {}
void asin() {}
void asinf() {}
void acos() {}
void acosf() {}
void atan() {}
void atanf() {}
void atan2() {}
void atan2f() {}
void sinh() {}
void sinhf() {}
void cosh() {}
void coshf() {}
void tanh() {}
void tanhf() {}
void asinh() {}
void asinhf() {}
void acosh() {}
void acoshf() {}
void atanh() {}
void atanhf() {}
void log() {}
void logf() {}
void log1p() {}
void log1pf() {}
void log2() {}
void log2f() {}
void log10() {}
void log10f() {}
void exp() {}
void expf() {}
void expm1() {}
void expm1f() {}
void exp2() {}
void exp2f() {}
void ldexp() {}
void ldexpf() {}
void frexpf() {}
void frexp() {}
void pow() {}
void powf() {}
void sqrt() {}
void sqrtf() {}
void ceil() {}
void ceilf() {}
void floor() {}
void floorf() {}
void round() {}
void roundf() {}
void trunc() {}
void truncf() {}
void modff() {}
void lrint() {}
void lrintf() {}
void fmod() {}
void fmodf() {}
void fmax() {}
void fmaxf() {}
void fmin() {}
void fminf() {}
void mmap() {}
void munmap() {}
void if_nameindex() {}
void getaddrinfo() {}
void freeaddrinfo() {}
void gethostbyname() {}
void open() {}
void read() {}
void write() {}
void lseek() {}
void close() {}
void rename() {}
void getcwd() {}
void chdir() {}
void fcntl() {}
void flock() {}
void ftruncate() {}
void mkdir() {}
void fstat() {}
void stat() {}
void pthread_cond_init() {}
void pthread_cond_wait() {}
void pthread_cond_signal() {}
void pthread_cond_destroy() {}
void pthread_key_create() {}
void pthread_getspecific() {}
void pthread_setspecific() {}
void pthread_mutexattr_init() {}
void pthread_mutexattr_setpshared() {}
void pthread_mutexattr_settype() {}
void pthread_mutexattr_destroy() {}
void pthread_mutex_init() {}
void pthread_mutex_lock() {}
void pthread_mutex_trylock() {}
void pthread_mutex_unlock() {}
void pthread_mutex_destroy() {}
void pthread_once() {}
void pthread_attr_init() {}
void pthread_attr_setdetachstate() {}
void pthread_attr_getstacksize() {}
void pthread_attr_setstacksize() {}
void pthread_attr_destroy() {}
void pthread_create() {}
void pthread_equal() {}
void pthread_self() {}
void pthread_join() {}
void pthread_detach() {}
void pthread_setcanceltype() {}
void pthread_testcancel() {}
void pthread_mach_thread_np() {}
void pthread_getschedparam() {}
void pthread_setschedparam() {}
void sched_yield() {}
void sem_init() {}
void sem_destroy() {}
void sem_open() {}
void sem_post() {}
void sem_wait() {}
void sem_trywait() {}
void sem_close() {}
void sem_unlink() {}
void setjmp() {}
void longjmp() {}
void sigaction() {}
void signal() {}
void fopen() {}
void fread() {}
void fgetc() {}
void fgets() {}
void fputs() {}
void fputc() {}
void putc() {}
void fwrite() {}
void fseek() {}
void ftell() {}
void rewind() {}
void fsetpos() {}
void fgetpos() {}
void feof() {}
void clearerr() {}
void fflush() {}
void fclose() {}
void ferror() {}
void puts() {}
void putchar() {}
void remove() {}
void setbuf() {}
void fileno() {}
void sscanf() {}
void swscanf() {}
void vsscanf() {}
void snprintf() {}
void vprintf() {}
void vsnprintf() {}
void vsprintf() {}
void __sprintf_chk() {}
void sprintf() {}
void swprintf() {}
void vswprintf() {}
void printf() {}
void fprintf() {}
void vfprintf() {}
void malloc() {}
void malloc_size() {}
void calloc() {}
void realloc() {}
void free() {}
void atexit() {}
void atoi() {}
void atol() {}
void atof() {}
void strtod() {}
void srand() {}
void rand() {}
void srandom() {}
void random() {}
void arc4random() {}
void getenv() {}
void setenv() {}
void exit() {}
void bsearch() {}
void strtof() {}
void strtoul() {}
void strtol() {}
void realpath() {}
void realpath$DARWIN_EXTSN() {}
void mbstowcs() {}
void wcstombs() {}
void qsort() {}
void strtok() {}
void bzero() {}
void memset() {}
void __memset_chk() {}
void memcpy() {}
void memmove() {}
void memchr() {}
void memcmp() {}
void strlen() {}
void strcpy() {}
void __strcpy_chk() {}
void strcat() {}
void strcspn() {}
void __strcat_chk() {}
void strncpy() {}
void strsep() {}
void strdup() {}
void strcmp() {}
void strncmp() {}
void strcasecmp() {}
void strncasecmp() {}
void strncat() {}
void strstr() {}
void strchr() {}
void strrchr() {}
void strlcpy() {}
void statfs() {}
void ptrace() {}
void ftime() {}
void socket() {}
void ioctl() {}
void setsockopt() {}
void bind() {}
void listen() {}
void connect() {}
void select() {}
void accept() {}
void recv() {}
void recvfrom() {}
void send() {}
void sendto() {}
void shutdown() {}
void uname() {}
void sysctl() {}
void sysctlbyname() {}
void clock() {}
void time() {}
void tzset() {}
void gmtime_r() {}
void gmtime() {}
void mktime() {}
void localtime_r() {}
void localtime() {}
void gettimeofday() {}
void nanosleep() {}
void sleep() {}
void usleep() {}
void getpid() {}
void getppid() {}
void isatty() {}
void access() {}
void unlink() {}
void gethostname() {}
void getpagesize() {}
void getgid() {}
void btowc() {}
void wctob() {}
void wmemset() {}
void wmemcpy() {}
void wmemmove() {}
void wmemchr() {}
void wmemcmp() {}
void wcslen() {}
void wcscpy() {}
void wcscat() {}
void wcscspn() {}
void wcsncpy() {}
void wcsdup() {}
void wcscmp() {}
void wcsncmp() {}
void wcsncat() {}
void wcsstr() {}
void wcschr() {}
void wcsrchr() {}
void wcslcpy() {}
void objc_msgSend() {}
void objc_msgSend_stret() {}
void objc_msgSendSuper2() {}
void objc_getProperty() {}
void objc_setProperty() {}
void objc_copyStruct() {}
void objc_sync_enter() {}
void objc_sync_exit() {}
void sel_registerName() {}
void _Block_object_dispose() {}
void AudioComponentFindNext() {}
void AudioComponentInstanceNew() {}
void AudioComponentInstanceDispose() {}
void AudioFileOpenURL() {}
void AudioFileGetPropertyInfo() {}
void AudioFileGetProperty() {}
void AudioFileReadBytes() {}
void AudioFileReadPackets() {}
void AudioFileReadPacketData() {}
void AudioFileOpenWithCallbacks() {}
void AudioFileClose() {}
void AudioFileStreamOpen() {}
void AudioQueueNewOutput() {}
void AudioQueueGetParameter() {}
void AudioQueueSetParameter() {}
void AudioQueueAllocateBufferWithPacketDescriptions() {}
void AudioQueueAllocateBuffer() {}
void AudioQueueEnqueueBuffer() {}
void AudioQueueAddPropertyListener() {}
void AudioQueueRemovePropertyListener() {}
void AudioQueueGetPropertySize() {}
void AudioQueueGetProperty() {}
void AudioQueuePrime() {}
void AudioQueueStart() {}
void AudioQueuePause() {}
void AudioQueueStop() {}
void AudioQueueReset() {}
void AudioQueueFlush() {}
void AudioQueueFreeBuffer() {}
void AudioQueueDispose() {}
void AudioServicesGetProperty() {}
void AudioServicesPlaySystemSound() {}
void AudioSessionInitialize() {}
void AudioSessionGetProperty() {}
void AudioSessionGetPropertySize() {}
void AudioSessionSetProperty() {}
void AudioSessionSetActive() {}
void AudioSessionAddPropertyListener() {}
void AudioUnitInitialize() {}
void AudioUnitUninitialize() {}
void AudioUnitSetProperty() {}
void AudioUnitGetProperty() {}
void AudioOutputUnitStart() {}
void AudioOutputUnitStop() {}
void CFArrayCreateMutable() {}
void CFArrayGetCount() {}
void CFArrayGetValueAtIndex() {}
void CFArrayAppendValue() {}
void CFArrayRemoveValueAtIndex() {}
void CFDictionaryCreateMutable() {}
void CFDictionaryAddValue() {}
void CFDictionarySetValue() {}
void CFDictionaryRemoveValue() {}
void CFDictionaryRemoveAllValues() {}
void CFDictionaryGetValue() {}
void CFDictionaryGetCount() {}
void CFDictionaryGetKeysAndValues() {}
void CFBundleGetMainBundle() {}
void CFBundleGetValueForInfoDictionaryKey() {}
void CFBundleGetVersionNumber() {}
void CFBundleCopyBundleURL() {}
void CFBundleCopyResourcesDirectoryURL() {}
void CFBundleCopyResourceURL() {}
void CFBundleCopyBundleLocalizations() {}
void CFBundleCopyPreferredLocalizationsFromArray() {}
void CFSocketCreate() {}
void CFDataCreate() {}
void CFDataGetLength() {}
void CFDataGetBytePtr() {}
void CFDataGetBytes() {}
void CFLocaleCopyCurrent() {}
void CFLocaleCopyPreferredLanguages() {}
void CFLocaleCreateCanonicalLocaleIdentifierFromString() {}
void CFLocaleGetSystem() {}
void CFLocaleGetValue() {}
void CFRunLoopGetCurrent() {}
void CFRunLoopGetMain() {}
void CFRunLoopRunInMode() {}
void CFRunLoopTimerCreate() {}
void CFRunLoopAddTimer() {}
void CFRunLoopTimerInvalidate() {}
void CFStringAppendFormat() {}
void CFStringConvertEncodingToNSStringEncoding() {}
void CFStringConvertNSStringEncodingToEncoding() {}
void CFStringCreateMutable() {}
void CFStringCreateWithCString() {}
void CFStringCreateWithFormat() {}
void CFStringCreateWithFormatAndArguments() {}
void CFStringCompare() {}
void CFStringGetCStringPtr() {}
void CFStringGetCString() {}
void CFStringGetLength() {}
void CFStringFind() {}
void CFRetain() {}
void CFRelease() {}
void CFGetRetainCount() {}
void CFEqual() {}
void CFHash() {}
void CFURLGetFileSystemRepresentation() {}
void CFURLCreateFromFileSystemRepresentation() {}
void CFURLCopyPathExtension() {}
void CFURLCopyFileSystemPath() {}
void CFURLCreateCopyAppendingPathComponent() {}
void CFURLCreateCopyDeletingLastPathComponent() {}
void CFAbsoluteTimeGetCurrent() {}
void CFTimeZoneCopySystem() {}
void CFAbsoluteTimeGetGregorianDate() {}
void CFAbsoluteTimeGetDayOfWeek() {}
void CGAffineTransformIsIdentity() {}
void CGAffineTransformEqualToTransform() {}
void CGAffineTransformMake() {}
void CGAffineTransformMakeRotation() {}
void CGAffineTransformMakeScale() {}
void CGAffineTransformMakeTranslation() {}
void CGAffineTransformConcat() {}
void CGAffineTransformRotate() {}
void CGAffineTransformScale() {}
void CGAffineTransformTranslate() {}
void CGAffineTransformInvert() {}
void CGPointApplyAffineTransform() {}
void CGSizeApplyAffineTransform() {}
void CGRectApplyAffineTransform() {}
void CGBitmapContextCreate() {}
void CGBitmapContextCreateImage() {}
void CGBitmapContextGetData() {}
void CGBitmapContextGetWidth() {}
void CGBitmapContextGetHeight() {}
void CGColorRetain() {}
void CGColorRelease() {}
void CGColorCreate() {}
void CGColorSpaceCreateWithName() {}
void CGColorSpaceCreateDeviceRGB() {}
void CGColorSpaceCreateDeviceGray() {}
void CGColorSpaceRetain() {}
void CGColorSpaceRelease() {}
void CGColorSpaceGetModel() {}
void CGContextRetain() {}
void CGContextRelease() {}
void CGContextSetRGBFillColor() {}
void CGContextSetGrayFillColor() {}
void CGContextFillRect() {}
void CGContextClearRect() {}
void CGContextConcatCTM() {}
void CGContextGetCTM() {}
void CGContextRotateCTM() {}
void CGContextScaleCTM() {}
void CGContextTranslateCTM() {}
void CGContextDrawImage() {}
void CGContextSaveGState() {}
void CGContextRestoreGState() {}
void CGContextSetInterpolationQuality() {}
void CGDataProviderRetain() {}
void CGDataProviderRelease() {}
void CGDataProviderCreateWithData() {}
void CGDataProviderCopyData() {}
void CGPointEqualToPoint() {}
void CGSizeEqualToSize() {}
void CGRectEqualToRect() {}
void CGRectContainsPoint() {}
void CGRectIntersectsRect() {}
void CGImageRelease() {}
void CGImageRetain() {}
void CGImageCreateWithPNGDataProvider() {}
void CGImageGetAlphaInfo() {}
void CGImageGetColorSpace() {}
void CGImageGetWidth() {}
void CGImageGetHeight() {}
void CGImageGetBitsPerPixel() {}
void CGImageGetDataProvider() {}
void CGImageGetBitsPerComponent() {}
void DNSServiceBrowse() {}
void DNSServiceRefSockFD() {}
void NSStringFromRange() {}
void NSSetUncaughtExceptionHandler() {}
void NSHomeDirectory() {}
void NSTemporaryDirectory() {}
void NSSearchPathForDirectoriesInDomains() {}
void NSLog() {}
void NSLogv() {}
void NSStringFromSelector() {}
void NSSelectorFromString() {}
void NSClassFromString() {}
void NSStringFromClass() {}
void alcOpenDevice() {}
void alcCloseDevice() {}
void alcGetError() {}
void alcCreateContext() {}
void alcDestroyContext() {}
void alcProcessContext() {}
void alcSuspendContext() {}
void alcMakeContextCurrent() {}
void alcGetProcAddress() {}
void alGetError() {}
void alDistanceModel() {}
void alListenerf() {}
void alListener3f() {}
void alListenerfv() {}
void alListeneri() {}
void alListener3i() {}
void alListeneriv() {}
void alGetListenerf() {}
void alGetListener3f() {}
void alGetListenerfv() {}
void alGetListeneri() {}
void alGetListener3i() {}
void alGetListeneriv() {}
void alGenSources() {}
void alDeleteSources() {}
void alSourcef() {}
void alSource3f() {}
void alSourcefv() {}
void alSourcei() {}
void alSource3i() {}
void alSourceiv() {}
void alGetSourcef() {}
void alGetSource3f() {}
void alGetSourcefv() {}
void alGetSourcei() {}
void alGetSource3i() {}
void alGetSourceiv() {}
void alSourcePlay() {}
void alSourcePause() {}
void alSourceStop() {}
void alSourceRewind() {}
void alSourceQueueBuffers() {}
void alSourceUnqueueBuffers() {}
void alGenBuffers() {}
void alDeleteBuffers() {}
void alBufferData() {}
void alBufferDataStatic() {}
void alcMacOSXMixerOutputRate() {}
void alcMacOSXGetMixerOutputRate() {}
void alcGetContextsDevice() {}
void alcGetCurrentContext() {}
void alcGetEnumValue() {}
void alcGetIntegerv() {}
void alcGetString() {}
void alcIsExtensionPresent() {}
void alIsBuffer() {}
void alGetBufferf() {}
void alGetBufferi() {}
void alEnable() {}
void alDisable() {}
void alDopplerFactor() {}
void alDopplerVelocity() {}
void alGetBoolean() {}
void alGetBooleanv() {}
void alGetDouble() {}
void alGetDoublev() {}
void alGetFloat() {}
void alGetFloatv() {}
void alGetInteger() {}
void alGetIntegerv() {}
void alGetEnumValue() {}
void alGetProcAddress() {}
void alGetString() {}
void alIsExtensionPresent() {}
void alIsEnabled() {}
void alIsSource() {}
void alSourcePlayv() {}
void alSourcePausev() {}
void alSourceStopv() {}
void alSourceRewindv() {}
void alSpeedOfSound() {}
void glGetError() {}
void glEnable() {}
void glIsEnabled() {}
void glDisable() {}
void glClientActiveTexture() {}
void glEnableClientState() {}
void glDisableClientState() {}
void glGetBooleanv() {}
void glGetFloatv() {}
void glGetIntegerv() {}
void glGetPointerv() {}
void glGetTexEnviv() {}
void glGetTexEnvfv() {}
void glHint() {}
void glFinish() {}
void glFlush() {}
void glGetString() {}
void glAlphaFunc() {}
void glAlphaFuncx() {}
void glBlendFunc() {}
void glBlendEquationOES() {}
void glColorMask() {}
void glClipPlanef() {}
void glClipPlanex() {}
void glCullFace() {}
void glDepthFunc() {}
void glDepthMask() {}
void glDepthRangef() {}
void glDepthRangex() {}
void glFrontFace() {}
void glPolygonOffset() {}
void glPolygonOffsetx() {}
void glShadeModel() {}
void glScissor() {}
void glViewport() {}
void glLineWidth() {}
void glLineWidthx() {}
void glStencilFunc() {}
void glStencilOp() {}
void glStencilMask() {}
void glPointSize() {}
void glPointSizex() {}
void glPointParameterf() {}
void glPointParameterx() {}
void glPointParameterfv() {}
void glPointParameterxv() {}
void glFogf() {}
void glFogx() {}
void glFogfv() {}
void glFogxv() {}
void glLightf() {}
void glLightx() {}
void glLightfv() {}
void glLightxv() {}
void glLightModelf() {}
void glLightModelfv() {}
void glLightModelx() {}
void glLightModelxv() {}
void glMaterialf() {}
void glMaterialx() {}
void glMaterialfv() {}
void glMaterialxv() {}
void glIsBuffer() {}
void glGenBuffers() {}
void glDeleteBuffers() {}
void glBindBuffer() {}
void glBufferData() {}
void glBufferSubData() {}
void glColor4f() {}
void glColor4x() {}
void glColor4ub() {}
void glNormal3f() {}
void glNormal3x() {}
void glColorPointer() {}
void glNormalPointer() {}
void glTexCoordPointer() {}
void glVertexPointer() {}
void glDrawArrays() {}
void glDrawElements() {}
void glClear() {}
void glClearColor() {}
void glClearColorx() {}
void glClearDepthf() {}
void glClearDepthx() {}
void glClearStencil() {}
void glMatrixMode() {}
void glLoadIdentity() {}
void glLoadMatrixf() {}
void glLoadMatrixx() {}
void glMultMatrixf() {}
void glMultMatrixx() {}
void glPushMatrix() {}
void glPopMatrix() {}
void glOrthof() {}
void glOrthox() {}
void glFrustumf() {}
void glFrustumx() {}
void glRotatef() {}
void glRotatex() {}
void glScalef() {}
void glScalex() {}
void glTranslatef() {}
void glTranslatex() {}
void glPixelStorei() {}
void glReadPixels() {}
void glGenTextures() {}
void glDeleteTextures() {}
void glActiveTexture() {}
void glIsTexture() {}
void glBindTexture() {}
void glTexParameteri() {}
void glTexParameterf() {}
void glTexParameterx() {}
void glTexParameteriv() {}
void glTexParameterfv() {}
void glTexParameterxv() {}
void glTexImage2D() {}
void glTexSubImage2D() {}
void glCompressedTexImage2D() {}
void glCopyTexImage2D() {}
void glCopyTexSubImage2D() {}
void glTexEnvf() {}
void glTexEnvx() {}
void glTexEnvi() {}
void glTexEnvfv() {}
void glTexEnvxv() {}
void glTexEnviv() {}
void glGenFramebuffersOES() {}
void glGenRenderbuffersOES() {}
void glBindFramebufferOES() {}
void glBindRenderbufferOES() {}
void glRenderbufferStorageOES() {}
void glFramebufferRenderbufferOES() {}
void glFramebufferTexture2DOES() {}
void glGetFramebufferAttachmentParameterivOES() {}
void glGetRenderbufferParameterivOES() {}
void glCheckFramebufferStatusOES() {}
void glDeleteFramebuffersOES() {}
void glDeleteRenderbuffersOES() {}
void glGenerateMipmapOES() {}
void glGetBufferParameteriv() {}
void glMapBufferOES() {}
void glUnmapBufferOES() {}
void SCNetworkReachabilityCreateWithName() {}
void SCNetworkReachabilityCreateWithAddress() {}
void SCNetworkReachabilityGetFlags() {}
void SCNetworkReachabilitySetCallback() {}
void UIApplicationMain() {}
void CGPointFromString() {}
void CGSizeFromString() {}
void CGRectFromString() {}
void NSStringFromCGPoint() {}
void NSStringFromCGSize() {}
void NSStringFromCGRect() {}
void UIGraphicsPushContext() {}
void UIGraphicsPopContext() {}
void UIGraphicsGetCurrentContext() {}
void _DefaultRuneLocale() {}
void __stdinp() {}
void __stdoutp() {}
void __stderrp() {}
void mach_task_self_() {}
void vm_page_size() {}
void kCATransitionFade() {}
void kCATransitionMoveIn() {}
void kCATransitionPush() {}
void kCATransitionReveal() {}
void kCAFilterLinear() {}
void kCAFilterNearest() {}
void kCAFilterTrilinear() {}
void kCAMediaTimingFunctionDefault() {}
void kCAMediaTimingFunctionEaseIn() {}
void kCAMediaTimingFunctionEaseInEaseOut() {}
void kCAMediaTimingFunctionEaseOut() {}
void kCAMediaTimingFunctionLinear() {}
void kCFAllocatorDefault() {}
void kCFBundleVersionKey() {}
void kCFTypeDictionaryKeyCallBacks() {}
void kCFTypeDictionaryValueCallBacks() {}
void kCFLocaleCountryCode() {}
void kCFRunLoopCommonModes() {}
void kCFRunLoopDefaultMode() {}
void CGAffineTransformIdentity() {}
void kCGColorSpaceGenericRGB() {}
void kCGColorSpaceGenericGray() {}
void CGSizeZero() {}
void CGPointZero() {}
void CGRectZero() {}
void GKPlayerAuthenticationDidChangeNotificationName() {}
void NSLocalizedDescriptionKey() {}
void NSOSStatusErrorDomain() {}
void NSCharacterConversionException() {}
void NSDecimalNumberDivideByZeroException() {}
void NSDecimalNumberExactnessException() {}
void NSDecimalNumberOverflowException() {}
void NSDecimalNumberUnderflowException() {}
void NSDestinationInvalidException() {}
void NSFileHandleOperationException() {}
void NSGenericException() {}
void NSInternalInconsistencyException() {}
void NSInvalidArchiveOperationException() {}
void NSInvalidArgumentException() {}
void NSInvalidReceivePortException() {}
void NSInvalidSendPortException() {}
void NSInvalidUnarchiveOperationException() {}
void NSInvocationOperationCancelledException() {}
void NSInvocationOperationVoidResultException() {}
void NSMallocException() {}
void NSObjectInaccessibleException() {}
void NSObjectNotAvailableException() {}
void NSOldStyleException() {}
void NSParseErrorException() {}
void NSPortReceiveException() {}
void NSPortSendException() {}
void NSPortTimeoutException() {}
void NSRangeException() {}
void NSUndefinedKeyException() {}
void NSInconsistentArchiveException() {}
void NSPPDIncludeNotFoundException() {}
void NSPPDIncludeStackOverflowException() {}
void NSPPDIncludeStackUnderflowException() {}
void NSPPDParseException() {}
void NSRTFPropertyStackOverflowException() {}
void NSTIFFException() {}
void NSAbortModalException() {}
void NSAbortPrintingException() {}
void NSAccessibilityException() {}
void NSAppKitIgnoredException() {}
void NSAppKitVirtualMemoryException() {}
void NSBadBitmapParametersException() {}
void NSBadComparisonException() {}
void NSBadRTFColorTableException() {}
void NSBadRTFDirectiveException() {}
void NSBadRTFFontTableException() {}
void NSBadRTFStyleSheetException() {}
void NSBrowserIllegalDelegateException() {}
void NSColorListIOException() {}
void NSColorListNotEditableException() {}
void NSDraggingException() {}
void NSFontUnavailableException() {}
void NSIllegalSelectorException() {}
void NSImageCacheException() {}
void NSNibLoadingException() {}
void NSPasteboardCommunicationException() {}
void NSPrintOperationExistsException() {}
void NSPrintPackageException() {}
void NSPrintingCommunicationException() {}
void NSTextLineTooLongException() {}
void NSTextNoSelectionException() {}
void NSTextReadException() {}
void NSTextWriteException() {}
void NSTypedStreamVersionException() {}
void NSWindowServerCommunicationException() {}
void NSWordTablesReadException() {}
void NSWordTablesWriteException() {}
void UIViewControllerHierarchyInconsistencyException() {}
void UIApplicationInvalidInterfaceOrientationException() {}
void NSFileModificationDate() {}
void NSFileSize() {}
void NSFileSystemFreeSize() {}
void NSKeyedArchiveRootObjectKey() {}
void NSLocaleCountryCode() {}
void NSRunLoopCommonModes() {}
void NSDefaultRunLoopMode() {}
void MPMoviePlayerPlaybackDidFinishNotification() {}
void MPMoviePlayerContentPreloadDidFinishNotification() {}
void MPMoviePlayerScalingModeDidChangeNotification() {}
void MPMusicPlayerControllerNowPlayingItemDidChangeNotification() {}
void MPMusicPlayerControllerPlaybackStateDidChangeNotification() {}
void kEAGLDrawablePropertyColorFormat() {}
void kEAGLDrawablePropertyRetainedBacking() {}
void kEAGLColorFormatRGBA8() {}
void kEAGLColorFormatRGB565() {}
void UIApplicationDidReceiveMemoryWarningNotification() {}
void UIApplicationLaunchOptionsRemoteNotificationKey() {}
void UIApplicationDidEnterBackgroundNotification() {}
void UIDeviceOrientationDidChangeNotification() {}
void UITextFieldTextDidChangeNotification() {}
void UIKeyboardWillShowNotification() {}
void UIKeyboardDidShowNotification() {}
void UIKeyboardWillHideNotification() {}
void UIKeyboardDidHideNotification() {}
void UIKeyboardBoundsUserInfoKey() {}
void OBJC_CLASS_$__touchHLE_AppPickerDelegate() {}
void OBJC_METACLASS_$__touchHLE_AppPickerDelegate() {}
void OBJC_CLASS_$_CAAnimation() {}
void OBJC_METACLASS_$_CAAnimation() {}
void OBJC_CLASS_$_CAPropertyAnimation() {}
void OBJC_METACLASS_$_CAPropertyAnimation() {}
void OBJC_CLASS_$_CABasicAnimation() {}
void OBJC_METACLASS_$_CABasicAnimation() {}
void OBJC_CLASS_$_CATransition() {}
void OBJC_METACLASS_$_CATransition() {}
void OBJC_CLASS_$_CAEAGLLayer() {}
void OBJC_METACLASS_$_CAEAGLLayer() {}
void OBJC_CLASS_$_CALayer() {}
void OBJC_METACLASS_$_CALayer() {}
void OBJC_CLASS_$_CAMediaTimingFunction() {}
void OBJC_METACLASS_$_CAMediaTimingFunction() {}
void OBJC_CLASS_$__touchHLE_CGDataProvider() {}
void OBJC_METACLASS_$__touchHLE_CGDataProvider() {}
void OBJC_CLASS_$__touchHLE_CGColor() {}
void OBJC_METACLASS_$__touchHLE_CGColor() {}
void OBJC_CLASS_$__touchHLE_CGColorSpace() {}
void OBJC_METACLASS_$__touchHLE_CGColorSpace() {}
void OBJC_CLASS_$__touchHLE_CGContext() {}
void OBJC_METACLASS_$__touchHLE_CGContext() {}
void OBJC_CLASS_$__touchHLE_CGImage() {}
void OBJC_METACLASS_$__touchHLE_CGImage() {}
void OBJC_CLASS_$__touchHLE_CFTimerTarget() {}
void OBJC_METACLASS_$__touchHLE_CFTimerTarget() {}
void OBJC_CLASS_$_CLLocationManager() {}
void OBJC_METACLASS_$_CLLocationManager() {}
void OBJC_CLASS_$_CLHeading() {}
void OBJC_METACLASS_$_CLHeading() {}
void OBJC_CLASS_$_GKLocalPlayer() {}
void OBJC_METACLASS_$_GKLocalPlayer() {}
void OBJC_CLASS_$_GKScore() {}
void OBJC_METACLASS_$_GKScore() {}
void OBJC_CLASS_$_NSArray() {}
void OBJC_METACLASS_$_NSArray() {}
void OBJC_CLASS_$_NSMutableArray() {}
void OBJC_METACLASS_$_NSMutableArray() {}
void OBJC_CLASS_$__touchHLE_NSArray() {}
void OBJC_METACLASS_$__touchHLE_NSArray() {}
void OBJC_CLASS_$__touchHLE_NSArray_non_retaining() {}
void OBJC_METACLASS_$__touchHLE_NSArray_non_retaining() {}
void OBJC_CLASS_$__touchHLE_NSArray_ObjectEnumerator() {}
void OBJC_METACLASS_$__touchHLE_NSArray_ObjectEnumerator() {}
void OBJC_CLASS_$__touchHLE_NSMutableArray() {}
void OBJC_METACLASS_$__touchHLE_NSMutableArray() {}
void OBJC_CLASS_$__touchHLE_NSMutableArray_non_retaining() {}
void OBJC_METACLASS_$__touchHLE_NSMutableArray_non_retaining() {}
void OBJC_CLASS_$_NSAutoreleasePool() {}
void OBJC_METACLASS_$_NSAutoreleasePool() {}
void OBJC_CLASS_$_NSBundle() {}
void OBJC_METACLASS_$_NSBundle() {}
void OBJC_CLASS_$_NSCharacterSet() {}
void OBJC_METACLASS_$_NSCharacterSet() {}
void OBJC_CLASS_$__touchHLE_NSCharacterSet() {}
void OBJC_METACLASS_$__touchHLE_NSCharacterSet() {}
void OBJC_CLASS_$_NSCoder() {}
void OBJC_METACLASS_$_NSCoder() {}
void OBJC_CLASS_$_NSData() {}
void OBJC_METACLASS_$_NSData() {}
void OBJC_CLASS_$_NSMutableData() {}
void OBJC_METACLASS_$_NSMutableData() {}
void OBJC_CLASS_$_NSDate() {}
void OBJC_METACLASS_$_NSDate() {}
void OBJC_CLASS_$_NSDateFormatter() {}
void OBJC_METACLASS_$_NSDateFormatter() {}
void OBJC_CLASS_$_NSDictionary() {}
void OBJC_METACLASS_$_NSDictionary() {}
void OBJC_CLASS_$_NSMutableDictionary() {}
void OBJC_METACLASS_$_NSMutableDictionary() {}
void OBJC_CLASS_$__touchHLE_NSDictionary() {}
void OBJC_METACLASS_$__touchHLE_NSDictionary() {}
void OBJC_CLASS_$__touchHLE_NSMutableDictionary() {}
void OBJC_METACLASS_$__touchHLE_NSMutableDictionary() {}
void OBJC_CLASS_$__touchHLE_NSMutableDictionary_non_retaining() {}
void OBJC_METACLASS_$__touchHLE_NSMutableDictionary_non_retaining() {}
void OBJC_CLASS_$_NSEnumerator() {}
void OBJC_METACLASS_$_NSEnumerator() {}
void OBJC_CLASS_$_NSError() {}
void OBJC_METACLASS_$_NSError() {}
void OBJC_CLASS_$_NSFileHandle() {}
void OBJC_METACLASS_$_NSFileHandle() {}
void OBJC_CLASS_$_NSFileManager() {}
void OBJC_METACLASS_$_NSFileManager() {}
void OBJC_CLASS_$_NSDirectoryEnumerator() {}
void OBJC_METACLASS_$_NSDirectoryEnumerator() {}
void OBJC_CLASS_$_NSKeyedUnarchiver() {}
void OBJC_METACLASS_$_NSKeyedUnarchiver() {}
void OBJC_CLASS_$_NSLocale() {}
void OBJC_METACLASS_$_NSLocale() {}
void OBJC_CLASS_$_NSLock() {}
void OBJC_METACLASS_$_NSLock() {}
void OBJC_CLASS_$_NSNotification() {}
void OBJC_METACLASS_$_NSNotification() {}
void OBJC_CLASS_$_NSNotificationCenter() {}
void OBJC_METACLASS_$_NSNotificationCenter() {}
void OBJC_CLASS_$_NSNull() {}
void OBJC_METACLASS_$_NSNull() {}
void OBJC_CLASS_$_NSObject() {}
void OBJC_METACLASS_$_NSObject() {}
void OBJC_CLASS_$_NSProcessInfo() {}
void OBJC_METACLASS_$_NSProcessInfo() {}
void OBJC_CLASS_$_NSPropertyListSerialization() {}
void OBJC_METACLASS_$_NSPropertyListSerialization() {}
void OBJC_CLASS_$_NSRunLoop() {}
void OBJC_METACLASS_$_NSRunLoop() {}
void OBJC_CLASS_$_NSScanner() {}
void OBJC_METACLASS_$_NSScanner() {}
void OBJC_CLASS_$__touchHLE_NSScanner() {}
void OBJC_METACLASS_$__touchHLE_NSScanner() {}
void OBJC_CLASS_$_NSSet() {}
void OBJC_METACLASS_$_NSSet() {}
void OBJC_CLASS_$_NSMutableSet() {}
void OBJC_METACLASS_$_NSMutableSet() {}
void OBJC_CLASS_$__touchHLE_NSSet() {}
void OBJC_METACLASS_$__touchHLE_NSSet() {}
void OBJC_CLASS_$__touchHLE_NSMutableSet() {}
void OBJC_METACLASS_$__touchHLE_NSMutableSet() {}
void OBJC_CLASS_$_NSString() {}
void OBJC_METACLASS_$_NSString() {}
void OBJC_CLASS_$_NSMutableString() {}
void OBJC_METACLASS_$_NSMutableString() {}
void OBJC_CLASS_$__touchHLE_NSString() {}
void OBJC_METACLASS_$__touchHLE_NSString() {}
void OBJC_CLASS_$__touchHLE_NSString_Static() {}
void OBJC_METACLASS_$__touchHLE_NSString_Static() {}
void OBJC_CLASS_$__touchHLE_NSString_CFConstantString_UTF8() {}
void OBJC_METACLASS_$__touchHLE_NSString_CFConstantString_UTF8() {}
void OBJC_CLASS_$__touchHLE_NSString_CFConstantString_UTF16() {}
void OBJC_METACLASS_$__touchHLE_NSString_CFConstantString_UTF16() {}
void OBJC_CLASS_$__touchHLE_NSMutableString() {}
void OBJC_METACLASS_$__touchHLE_NSMutableString() {}
void OBJC_CLASS_$_NSThread() {}
void OBJC_METACLASS_$_NSThread() {}
void OBJC_CLASS_$_NSTimer() {}
void OBJC_METACLASS_$_NSTimer() {}
void OBJC_CLASS_$_NSTimeZone() {}
void OBJC_METACLASS_$_NSTimeZone() {}
void OBJC_CLASS_$_NSURL() {}
void OBJC_METACLASS_$_NSURL() {}
void OBJC_CLASS_$_NSURLCache() {}
void OBJC_METACLASS_$_NSURLCache() {}
void OBJC_CLASS_$_NSURLConnection() {}
void OBJC_METACLASS_$_NSURLConnection() {}
void OBJC_CLASS_$_NSURLRequest() {}
void OBJC_METACLASS_$_NSURLRequest() {}
void OBJC_CLASS_$_NSMutableURLRequest() {}
void OBJC_METACLASS_$_NSMutableURLRequest() {}
void OBJC_CLASS_$_NSUserDefaults() {}
void OBJC_METACLASS_$_NSUserDefaults() {}
void OBJC_CLASS_$_NSValue() {}
void OBJC_METACLASS_$_NSValue() {}
void OBJC_CLASS_$_NSNumber() {}
void OBJC_METACLASS_$_NSNumber() {}
void OBJC_CLASS_$_NSXMLParser() {}
void OBJC_METACLASS_$_NSXMLParser() {}
void OBJC_CLASS_$_AVAudioPlayer() {}
void OBJC_METACLASS_$_AVAudioPlayer() {}
void OBJC_CLASS_$_MPMoviePlayerController() {}
void OBJC_METACLASS_$_MPMoviePlayerController() {}
void OBJC_CLASS_$_MPMusicPlayerController() {}
void OBJC_METACLASS_$_MPMusicPlayerController() {}
void OBJC_CLASS_$_MPMediaLibrary() {}
void OBJC_METACLASS_$_MPMediaLibrary() {}
void OBJC_CLASS_$_MPMediaPickerController() {}
void OBJC_METACLASS_$_MPMediaPickerController() {}
void OBJC_CLASS_$_MPMediaQuery() {}
void OBJC_METACLASS_$_MPMediaQuery() {}
void OBJC_CLASS_$_EAGLContext() {}
void OBJC_METACLASS_$_EAGLContext() {}
void OBJC_CLASS_$__touchHLE_SCNetworkReachability() {}
void OBJC_METACLASS_$__touchHLE_SCNetworkReachability() {}
void OBJC_CLASS_$_SKPaymentQueue() {}
void OBJC_METACLASS_$_SKPaymentQueue() {}
void OBJC_CLASS_$_SKProduct() {}
void OBJC_METACLASS_$_SKProduct() {}
void OBJC_CLASS_$_SKProductsRequest() {}
void OBJC_METACLASS_$_SKProductsRequest() {}
void OBJC_CLASS_$_UIAccelerometer() {}
void OBJC_METACLASS_$_UIAccelerometer() {}
void OBJC_CLASS_$_UIAcceleration() {}
void OBJC_METACLASS_$_UIAcceleration() {}
void OBJC_CLASS_$_UIActivityIndicatorView() {}
void OBJC_METACLASS_$_UIActivityIndicatorView() {}
void OBJC_CLASS_$_UIApplication() {}
void OBJC_METACLASS_$_UIApplication() {}
void OBJC_CLASS_$_UIColor() {}
void OBJC_METACLASS_$_UIColor() {}
void OBJC_CLASS_$_UICGColor() {}
void OBJC_METACLASS_$_UICGColor() {}
void OBJC_CLASS_$_UIDeviceRGBColor() {}
void OBJC_METACLASS_$_UIDeviceRGBColor() {}
void OBJC_CLASS_$__touchHLE_UIColor_Static() {}
void OBJC_METACLASS_$__touchHLE_UIColor_Static() {}
void OBJC_CLASS_$_UIDevice() {}
void OBJC_METACLASS_$_UIDevice() {}
void OBJC_CLASS_$_UIEvent() {}
void OBJC_METACLASS_$_UIEvent() {}
void OBJC_CLASS_$_UIFont() {}
void OBJC_METACLASS_$_UIFont() {}
void OBJC_CLASS_$_UIImage() {}
void OBJC_METACLASS_$_UIImage() {}
void OBJC_CLASS_$_UIImagePickerController() {}
void OBJC_METACLASS_$_UIImagePickerController() {}
void OBJC_CLASS_$_UINib() {}
void OBJC_METACLASS_$_UINib() {}
void OBJC_CLASS_$_UIProxyObject() {}
void OBJC_METACLASS_$_UIProxyObject() {}
void OBJC_CLASS_$_UIClassSwapper() {}
void OBJC_METACLASS_$_UIClassSwapper() {}
void OBJC_CLASS_$_UIRuntimeConnection() {}
void OBJC_METACLASS_$_UIRuntimeConnection() {}
void OBJC_CLASS_$_UIRuntimeEventConnection() {}
void OBJC_METACLASS_$_UIRuntimeEventConnection() {}
void OBJC_CLASS_$_UIRuntimeOutletConnection() {}
void OBJC_METACLASS_$_UIRuntimeOutletConnection() {}
void OBJC_CLASS_$_UIResponder() {}
void OBJC_METACLASS_$_UIResponder() {}
void OBJC_CLASS_$_UIScreen() {}
void OBJC_METACLASS_$_UIScreen() {}
void OBJC_CLASS_$_UITouch() {}
void OBJC_METACLASS_$_UITouch() {}
void OBJC_CLASS_$_UIView() {}
void OBJC_METACLASS_$_UIView() {}
void OBJC_CLASS_$_UIAlertView() {}
void OBJC_METACLASS_$_UIAlertView() {}
void OBJC_CLASS_$_UIControl() {}
void OBJC_METACLASS_$_UIControl() {}
void OBJC_CLASS_$_UIButton() {}
void OBJC_METACLASS_$_UIButton() {}
void OBJC_CLASS_$_UIRoundedRectButton() {}
void OBJC_METACLASS_$_UIRoundedRectButton() {}
void OBJC_CLASS_$_UIButtonContent() {}
void OBJC_METACLASS_$_UIButtonContent() {}
void OBJC_CLASS_$_UISegmentedControl() {}
void OBJC_METACLASS_$_UISegmentedControl() {}
void OBJC_CLASS_$_UISegment() {}
void OBJC_METACLASS_$_UISegment() {}
void OBJC_CLASS_$_UISlider() {}
void OBJC_METACLASS_$_UISlider() {}
void OBJC_CLASS_$_UITextField() {}
void OBJC_METACLASS_$_UITextField() {}
void OBJC_CLASS_$_UISwitch() {}
void OBJC_METACLASS_$_UISwitch() {}
void OBJC_CLASS_$_UIImageView() {}
void OBJC_METACLASS_$_UIImageView() {}
void OBJC_CLASS_$_UILabel() {}
void OBJC_METACLASS_$_UILabel() {}
void OBJC_CLASS_$_UIPickerView() {}
void OBJC_METACLASS_$_UIPickerView() {}
void OBJC_CLASS_$_UIScrollView() {}
void OBJC_METACLASS_$_UIScrollView() {}
void OBJC_CLASS_$_UITextView() {}
void OBJC_METACLASS_$_UITextView() {}
void OBJC_CLASS_$_UIWebView() {}
void OBJC_METACLASS_$_UIWebView() {}
void OBJC_CLASS_$_UIWindow() {}
void OBJC_METACLASS_$_UIWindow() {}
void OBJC_CLASS_$_UIViewController() {}
void OBJC_METACLASS_$_UIViewController() {}
void OBJC_CLASS_$_UINavigationController() {}
void OBJC_METACLASS_$_UINavigationController() {}
void _objc_empty_cache() {}
void _objc_empty_vtable() {}
void strerror() {}
void fsctl() {}
void srandomdev() {}
void confstr() {}
void strlcat() {}
void pwrite() {}
void utimes() {}
void pread() {}
void fchmod() {}
void dlerror() {}
void fsync() {}
