set(CCTOOLS_SOURCE_DIR "${SOURCES}/cctools-port")
set(CCTOOLS_BUILD_DIR "${CMAKE_BINARY_DIR}/cctools-build")
set(CCTOOLS_BUILD_PREFIX "${CMAKE_BINARY_DIR}/cctools")

include(ExternalProject)

ExternalProject_Add(
    cctools_port
    SOURCE_DIR ${CCTOOLS_SOURCE_DIR}
    BINARY_DIR ${CCTOOLS_BUILD_DIR}
    INSTALL_DIR ${CCTOOLS_BUILD_PREFIX}
    CMAKE_ARGS
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_INSTALL_PREFIX=${CCTOOLS_BUILD_PREFIX}
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
)

install(
    DIRECTORY ${CMAKE_BINARY_DIR}/cctools/bin/
    DESTINATION ${SDK_PATH}/usr/bin
    USE_SOURCE_PERMISSIONS
)
