set(CSU_SOURCE_DIR "${SOURCES}/csu")
set(CSU_BINARY_DIR "${CMAKE_BINARY_DIR}/csu-build")
set(CSU_INSTALL_DIR "${CMAKE_BINARY_DIR}/csu")

include(ExternalProject)

ExternalProject_Add(
    csu
    SOURCE_DIR ${CSU_SOURCE_DIR}
    BINARY_DIR ${CSU_BINARY_DIR}
    INSTALL_DIR ${CSU_INSTALL_DIR}
    CMAKE_ARGS
        -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
        -DCMAKE_INSTALL_PREFIX=${CSU_INSTALL_DIR}
)

install(
    DIRECTORY ${CSU_INSTALL_DIR}/lib
    DESTINATION usr
)