set(LIBC_SOURCE_DIR "${SOURCES}/libc-stub")
set(LIBC_BINARY_DIR "${CMAKE_BINARY_DIR}/libc-stub-build")
set(LIBC_INSTALL_DIR "${CMAKE_BINARY_DIR}/libc-stub")

include(ExternalProject)

ExternalProject_Add(
    libc_stub
    SOURCE_DIR ${LIBC_SOURCE_DIR}
    BINARY_DIR ${LIBC_BINARY_DIR}
    INSTALL_DIR ${LIBC_INSTALL_DIR}
    CMAKE_ARGS
        -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
        -DCMAKE_INSTALL_PREFIX=${LIBC_INSTALL_DIR}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
)

install(DIRECTORY ${LIBC_INSTALL_DIR}/lib DESTINATION usr)
