install(
    FILES
        "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES/MPL-2.0"
        "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES/APSL"
        "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES/GPLv2"
    DESTINATION "${SDK_PATH}/LICENSES"
    COMPONENT licenses
)

install(
    FILES "${CMAKE_CURRENT_SOURCE_DIR}/README.md"
    DESTINATION "${SDK_PATH}/"
    COMPONENT licenses
)

if(WIN32)
    install(
        FILES
            "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES/MIT.mman"
            "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES/COPYING.dlfcn"
            "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES/COPYING.libc++"
            "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES/COPYING.libgcc"
            "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES/COPYING.winpthreads"
        DESTINATION "${SDK_PATH}/LICENSES"
        COMPONENT licenses
    )
endif()
