set(CMAKE_SHARED_LIBRARY_PREFIX "lib")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".dylib")
set(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "-shared")
set(CMAKE_PLATFORM_HAS_SHARED_LIBRARY TRUE)
set(CMAKE_SUPPORTS_SHARED_LIBRARIES TRUE)
set(CMAKE_LINK_LIBRARY_SUFFIX "")

set(CMAKE_STATIC_LIBRARY_PREFIX "lib")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".a")

set(CMAKE_EXECUTABLE_SUFFIX "")

set(CMAKE_LINK_DEPENDS_NO_SHARED TRUE)

set(CMAKE_CROSSCOMPILING TRUE)
set(CMAKE_SYSTEM_LOADED 1)

# Force CMake to use custom linker
set(CMAKE_C_CREATE_SHARED_LIBRARY
    "<CMAKE_LINKER> <LINK_FLAGS> -o <TARGET> <OBJECTS>"
)

set(CMAKE_CXX_CREATE_SHARED_LIBRARY
    "<CMAKE_LINKER> <LINK_FLAGS> -o <TARGET> <OBJECTS>"
)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
