set(CMAKE_SHARED_LIBRARY_PREFIX "lib")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".dylib")
set(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "-shared")
set(CMAKE_PLATFORM_HAS_SHARED_LIBRARY TRUE)
set(CMAKE_SUPPORTS_SHARED_LIBRARIES TRUE)
set(CMAKE_LINK_LIBRARY_SUFFIX "")

set(CMAKE_STATIC_LIBRARY_PREFIX "lib")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".a")

set(CMAKE_EXECUTABLE_SUFFIX "")

set(CMAKE_LINK_DEPENDS_NO_SHARED TRUE)

set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_STANDARD_LIBRARIES_INIT "-lSystem -lgcc_s.1")
set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "${CMAKE_C_STANDARD_LIBRARIES_INIT}")

set(CMAKE_C_OSX_COMPATIBILITY_VERSION_FLAG "-compatibility_version ")
set(CMAKE_CXX_OSX_COMPATIBILITY_VERSION_FLAG
    "${CMAKE_C_OSX_COMPATIBILITY_VERSION_FLAG}"
)

set(CMAKE_C_OSX_CURRENT_VERSION_FLAG "-current_version ")
set(CMAKE_CXX_OSX_CURRENT_VERSION_FLAG "${CMAKE_C_OSX_CURRENT_VERSION_FLAG}")

set(CMAKE_SYSTEM_LOADED 1)
