name: Build common 3.0 SDK

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux-x86_64
            shell: bash

          - os: windows-latest
            platform: windows-x86_64
            shell: msys2 {0}
            env:
              CC: clang
              CXX: clang++

          - os: macos-latest
            platform: macOS-universal
            cmake_args: "-DCMAKE_OSX_ARCHITECTURES=\"arm64;x86_64\""
            shell: bash

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'true'

    - name: Setup Windows Environment
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          git
          patch
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-clang
          mingw-w64-ucrt-x86_64-dlfcn
          mingw-w64-ucrt-x86_64-llvm

    - name: Configure CMake
      run: cmake ${{ matrix.cmake_args || '' }} -B ${{github.workspace}}/build
      env: ${{ matrix.env || fromJSON('{}') }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Create SDK
      run: cmake --install ${{github.workspace}}/build

    - name: Bundle SDK
      run: tar -czf common-3.0.sdk-${{ matrix.platform }}.tar.gz common-3.0.sdk/

    - uses: actions/upload-artifact@v4
      with:
        name: common-3.0.sdk-${{ matrix.platform }}
        path: common-3.0.sdk

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: common-3.0.sdk-${{ matrix.platform }}.tar.gz
